## 練習時間
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

## import 需要的套件

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [2]:
wine = datasets.load_wine()
boston = datasets.load_boston()
breast_cancer = datasets.load_breast_cancer()

### Linear regssion

In [7]:
data = boston.data
target = boston.target
print(data.shape)
print(target.shape)

(506, 13)
(506,)


In [21]:
X_train, X_Valid, y_train, y_Valid = train_test_split(data, target, test_size=0.25)
print(X_train.shape)
print(X_Valid.shape)

reg = linear_model.LinearRegression()

reg.fit(X_train, y_train)

y_pred = reg.predict(X_Valid)

(379, 13)
(127, 13)


In [18]:
print('Coefficients: ', '\n', reg.coef_, '\n')
print('Intercepts: ', reg.intercept_, '\n')

print("Mean squared error: %.2f"
      % mean_squared_error(y_Valid, y_pred))

Coefficients:  
 [-8.91005812e-02  3.59447012e-02  1.71594380e-03  2.35168661e+00
 -2.16482906e+01  3.76251669e+00  6.72231641e-04 -1.57014482e+00
  2.90496805e-01 -1.20848225e-02 -1.01579879e+00  9.31511322e-03
 -4.81721301e-01] 

Intercepts:  40.12864315382319 

Mean squared error: 24.82


### Logistics regression

In [24]:
data = wine.data
target = wine.target
print(data.shape)
print(data, '\n')
print(target.shape)
print(target, '\n')
print(wine.feature_names, '\n')

(178, 13)
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] 

(178,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] 

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

In [25]:
X_train, X_Valid, y_train, y_Valid = train_test_split(data, target, test_size=0.25)
print(X_train.shape)
print(X_Valid.shape)

clf = linear_model.LogisticRegression()

clf.fit(X_train, y_train)

y_pred = clf.predict(X_Valid)

(133, 13)
(45, 13)


In [26]:
acc = accuracy_score(y_Valid, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.9111111111111111
