In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])
print(X.shape)
print(X)

#Output
y = np.array([[1], [1], [0]])
print(y.shape)

(3, 4)
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
(3, 1)


In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [3]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
print(inputlayer_neurons)
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

4


In [4]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
print(wh)
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
print(bh)
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) )  
print(wout)
bout = np.random.uniform( size = ( 1 , output_neurons ) )
print(bout)

[[0.1221966  0.17270693 0.81627509]
 [0.49044368 0.02204973 0.14827173]
 [0.62824806 0.66264992 0.32523807]
 [0.70601823 0.50765425 0.52728279]]
[[0.10835864 0.43091227 0.8721998 ]]
[[0.1173871 ]
 [0.4945353 ]
 [0.79883625]]
[[0.93191492]]


# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [6]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
#     print(hidden_layer_input1)

    hidden_layer_input = hidden_layer_input1 + bh
#     print(hidden_layer_input)

    hiddenlayer_activations =  sigmoid( hidden_layer_input )
#     print(hiddenlayer_activations)

    output_layer_input1 = np.dot(hiddenlayer_activations, wout)
#     print(output_layer_input1)

    output_layer_input = output_layer_input1 + bout
#     print(output_layer_input)

    output = sigmoid(output_layer_input)
#     print(output)
    
    #Backpropagation
    E = y - output
#     print(E)
    
    slope_output_layer = derivatives_sigmoid(output)
#     print(slope_output_layer)

    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
#     print(slope_hidden_layer)

    d_output = E * slope_output_layer
#     print(d_output)
    
    Error_at_hidden_layer = d_output.dot(wout.T)
#     print(Error_at_hidden_layer)
    
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
#     print(d_hiddenlayer)
    
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    
    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

output of Forward Propogation:
[[0.9840557 ]
 [0.97403799]
 [0.03448233]]
wout,bout of Backpropagation:
[[-3.46332259]
 [ 2.4445732 ]
 [ 2.98044422]],
[[-0.71299014]]
