In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path, 並讀取 app_train
dir_data = '../../Data/Part01/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

In [3]:
print(app_train.shape)
app_train.dtypes

(307511, 122)


SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
FLAG_OWN_REALTY                object
CNT_CHILDREN                    int64
AMT_INCOME_TOTAL              float64
AMT_CREDIT                    float64
AMT_ANNUITY                   float64
AMT_GOODS_PRICE               float64
NAME_TYPE_SUITE                object
NAME_INCOME_TYPE               object
NAME_EDUCATION_TYPE            object
NAME_FAMILY_STATUS             object
NAME_HOUSING_TYPE              object
REGION_POPULATION_RELATIVE    float64
DAYS_BIRTH                      int64
DAYS_EMPLOYED                   int64
DAYS_REGISTRATION             float64
DAYS_ID_PUBLISH                 int64
OWN_CAR_AGE                   float64
FLAG_MOBIL                      int64
FLAG_EMP_PHONE                  int64
FLAG_WORK_PHONE                 int64
FLAG_CONT_MOBILE                int64
FLAG_PHONE  

In [4]:
app_train.select_dtypes(include='int64')

SK_ID_CURR  TARGET  CNT_CHILDREN  DAYS_BIRTH  DAYS_EMPLOYED  \
0           100002       1             0       -9461           -637   
1           100003       0             0      -16765          -1188   
2           100004       0             0      -19046           -225   
3           100006       0             0      -19005          -3039   
4           100007       0             0      -19932          -3038   
5           100008       0             0      -16941          -1588   
6           100009       0             1      -13778          -3130   
7           100010       0             0      -18850           -449   
8           100011       0             0      -20099         365243   
9           100012       0             0      -14469          -2019   
10          100014       0             1      -10197           -679   
11          100015       0             0      -20417         365243   
12          100016       0             0      -13439          -2717   
13          100017       0             1      -14086          -3028   
14          100018       0             0      -14583           -203   
15          100019       0             0       -8728          -1157   
16          100020       0             0      -12931          -1317   
17          100021       0             1       -9776           -191   
18          100022       0             0      -17718          -7804   
19          100023       0             1      -11348          -2038   
20          100024       0             0      -18252          -4286   
21          100025       0             1      -14815          -1652   
22          100026       0             1      -11146          -4306   
23          100027       0             0      -24827         365243   
24          100029       0             2      -11286           -746   
25          100030       0             0      -19334          -3494   
26          100031       1             0      -18724          -2628   
27          100032       0             1      -15948          -1234   
28          100033       0             0       -9994          -1796   
29          100034       0             0      -10341          -1010   
...            ...     ...           ...         ...            ...   
307481      456225       1             0      -20644          -3147   
307482      456226       0             0      -14106           -226   
307483      456227       0             0      -24911         365243   
307484      456228       0             0      -12847           -328   
307485      456229       0             1      -11973           -670   
307486      456230       0             1      -16010          -1185   
307487      456231       0             0      -23125         365243   
307488      456232       0             0      -10092          -1218   
307489      456233       1             0      -16471           -286   
307490      456234       0             0       -9874          -1928   
307491      456235       0             2      -10976          -1953   
307492      456236       0             0      -20965          -1618   
307493      456237       0             0      -17533          -2306   
307494      456238       0             1      -14958          -6573   
307495      456239       0             0      -20922          -7438   
307496      456240       0             0      -17345          -2178   
307497      456241       0             0      -16679          -1222   
307498      456242       0             0      -19102          -3689   
307499      456243       0             0      -16988          -8694   
307500      456244       0             0      -20390          -5326   
307501      456245       0             3      -12961          -1046   
307502      456246       0             1      -16063          -8736   
307503      456247       0             0      -11870           -399   
307504      456248       0             0      -16705          -7258   
307505      456249       0      

In [5]:
app_train.select_dtypes(exclude=['int64', 'float64'])

NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0              Cash loans           M            N               Y   
1              Cash loans           F            N               N   
2         Revolving loans           M            Y               Y   
3              Cash loans           F            N               Y   
4              Cash loans           M            N               Y   
5              Cash loans           M            N               Y   
6              Cash loans           F            Y               Y   
7              Cash loans           M            Y               Y   
8              Cash loans           F            N               Y   
9         Revolving loans           M            N               Y   
10             Cash loans           F            N               Y   
11             Cash loans           F            N               Y   
12             Cash loans           F            N               Y   
13             Cash loans           M            Y               N   
14             Cash loans           F            N               Y   
15             Cash loans           M            Y               Y   
16             Cash loans           M            N               N   
17        Revolving loans           F            N               Y   
18        Revolving loans           F            N               Y   
19             Cash loans           F            N               Y   
20        Revolving loans           M            Y               Y   
21             Cash loans           F            Y               Y   
22             Cash loans           F            N               N   
23             Cash loans           F            N               Y   
24             Cash loans           M            Y               N   
25             Cash loans           F            N               Y   
26             Cash loans           F            N               Y   
27             Cash loans           M            N               Y   
28             Cash loans           M            Y               Y   
29        Revolving loans           M            N               Y   
...                   ...         ...          ...             ...   
307481         Cash loans           M            N               Y   
307482         Cash loans           F            Y               Y   
307483         Cash loans           F            N               Y   
307484         Cash loans           F            Y               N   
307485    Revolving loans           F            N               Y   
307486         Cash loans           F            Y               Y   
307487         Cash loans           M            N               Y   
307488         Cash loans           F            N               N   
307489         Cash loans           F            N               Y   
307490         Cash loans           M            N               Y   
307491         Cash loans           M            Y               Y   
307492         Cash loans           M            Y               Y   
307493         Cash loans           F            N               Y   
307494         Cash loans           M            Y               N   
307495         Cash loans           M            Y               N   
307496    Revolving loans           F            N               N   
307497         Cash loans           F            Y               Y   
307498         Cash loans           M            Y               Y   
307499         Cash loans           F            N               Y   
307500         Cash loans           F            N               Y   
307501         Cash loans           F            N               Y   
307502         Cash loans           F            N               Y   
307503         Cash loans           F            N               Y   
307504         Cash loans           F            N               Y   
307505         Cash loans           F            N               Y   
307506         Ca

In [6]:
app_train.select_dtypes(include=["int64"]).apply(pd.Series.nunique, axis = 0)

SK_ID_CURR                     307511
TARGET                              2
CNT_CHILDREN                       15
DAYS_BIRTH                      17460
DAYS_EMPLOYED                   12574
DAYS_ID_PUBLISH                  6168
FLAG_MOBIL                          2
FLAG_EMP_PHONE                      2
FLAG_WORK_PHONE                     2
FLAG_CONT_MOBILE                    2
FLAG_PHONE                          2
FLAG_EMAIL                          2
REGION_RATING_CLIENT                3
REGION_RATING_CLIENT_W_CITY         3
HOUR_APPR_PROCESS_START            24
REG_REGION_NOT_LIVE_REGION          2
REG_REGION_NOT_WORK_REGION          2
LIVE_REGION_NOT_WORK_REGION         2
REG_CITY_NOT_LIVE_CITY              2
REG_CITY_NOT_WORK_CITY              2
LIVE_CITY_NOT_WORK_CITY             2
FLAG_DOCUMENT_2                     2
FLAG_DOCUMENT_3                     2
FLAG_DOCUMENT_4                     2
FLAG_DOCUMENT_5                     2
FLAG_DOCUMENT_6                     2
FLAG_DOCUMEN

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [7]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
sub_train.head()

WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [8]:
# sub_train.as_matrix()
# sub_train.values
asub_train = np.array(sub_train)
asub_train[:,0]

array(['WEDNESDAY', 'MONDAY', 'MONDAY', ..., 'THURSDAY', 'WEDNESDAY',
       'THURSDAY'], dtype=object)

In [9]:
"""
Your Code Here
"""
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
LabelEn = LabelEncoder().fit_transform(asub_train[:,0])
print(LabelEn.shape)
print(LabelEn)

(307511,)
[6 1 1 ... 4 6 4]


In [10]:
OneHotEn = OneHotEncoder().fit_transform(LabelEn.reshape(-1,1))
print(OneHotEn.shape)
print(type(OneHotEn))
print(OneHotEn.toarray())

(307511, 7)
<class 'scipy.sparse.csr.csr_matrix'>
[[0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]]


In [11]:
sub_train=pd.DataFrame(OneHotEn.toarray(), columns=['FRIDAY','MONDAY','SATURDAY','SUNDAY','THURSDAY','TUESDAY','WEDNESDAY'])
sub_train.head()

FRIDAY  MONDAY  SATURDAY  SUNDAY  THURSDAY  TUESDAY  WEDNESDAY
0     0.0     0.0       0.0     0.0       0.0      0.0        1.0
1     0.0     1.0       0.0     0.0       0.0      0.0        0.0
2     0.0     1.0       0.0     0.0       0.0      0.0        0.0
3     0.0     0.0       0.0     0.0       0.0      0.0        1.0
4     0.0     0.0       0.0     0.0       1.0      0.0        0.0